version: '3.8'

services:
  subscriptions:
    image: vivek5239/subscriptions-app:latest
    container_name: subscriptions
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "3000:5000"
    volumes:
      - $DOCKERDIR/appdata/subscriptions:/data
    environment:
      - PORT=5000
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID

networks:
  t3_proxy:
    external: true
  socket_proxy:
    external: true
