version: '3.8'

services:
  reminders:
    build: .
    image: reminders-app
    container_name: reminders
    restart: unless-stopped
    ports:
      - "5005:5000"
    volumes:
      - ./data:/data
    environment:
      - PORT=5000
